name: Mirror Scorpion Build Monitor
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.0' # استخدام أحدث نسخة مستقرة لضمان التوافق
          channel: 'stable'
      - name: Install dependencies
        run: flutter pub get
      - name: Build APK
        run: flutter build apk --release
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Mirror-Scorpion-Release
          path: build/app/outputs/flutter-apk/app-release.apk
